[package]
name = "ebpfguard-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { git = "https://github.com/deepfence/aya-rs", branch = "btf-fixes", optional=true }

[lib]
path = "src/lib.rs"
